spring:
  datasource:
#    url: jdbc:h2:tcp://localhost/~/datajpa
    url: jdbc:tibero:thin:@127.0.0.1:8629:tibero
#    username: sa
#    password:
    username: tibero
    password: tmax
    driver-class-name: com.tmax.tibero.jdbc.TbDriver
#    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    database-platform: org.hibernate.dialect.Oracle10gDialect
  data:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 2000
#logging.level:
#  org.hibernate.SQL: debug
#  org.hibernate.type: trace